//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.OWChatServiceReference {
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class Exception : object, System.Xml.Serialization.IXmlSerializable, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("Exception", "http://source.owchat/");
        
        public System.Xml.XmlNode[] Nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public void ReadXml(System.Xml.XmlReader reader) {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer) {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema() {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas) {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class OWChatException : object, System.Xml.Serialization.IXmlSerializable, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("OWChatException", "http://source.owchat/");
        
        public System.Xml.XmlNode[] Nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public void ReadXml(System.Xml.XmlReader reader) {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer) {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema() {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas) {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://source.owchat/", ConfigurationName="OWChatServiceReference.OWChat")]
    public interface OWChat {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.sendMessageResponse sendMessage(ChatClient.OWChatServiceReference.sendMessageRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.OWChatException), Action="", Name="OWChatException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.registerUserResponse registerUser(ChatClient.OWChatServiceReference.registerUserRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.OWChatException), Action="", Name="OWChatException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.signInResponse signIn(ChatClient.OWChatServiceReference.signInRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.getAllUsersResponse getAllUsers(ChatClient.OWChatServiceReference.getAllUsersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.OWChatException), Action="", Name="OWChatException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.getAllFriendsResponse getAllFriends(ChatClient.OWChatServiceReference.getAllFriendsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.resetChatServerResponse resetChatServer(ChatClient.OWChatServiceReference.resetChatServerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.OWChatException), Action="", Name="OWChatException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.signOutResponse signOut(ChatClient.OWChatServiceReference.signOutRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.OWChatException), Action="", Name="OWChatException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.addAsFriendResponse addAsFriend(ChatClient.OWChatServiceReference.addAsFriendRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.OWChatException), Action="", Name="OWChatException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.receiveMessagesResponse receiveMessages(ChatClient.OWChatServiceReference.receiveMessagesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.OWChatException), Action="", Name="OWChatException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.unregisterUserResponse unregisterUser(ChatClient.OWChatServiceReference.unregisterUserRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChatClient.OWChatServiceReference.OWChatException), Action="", Name="OWChatException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ChatClient.OWChatServiceReference.removeFromFriendsResponse removeFromFriends(ChatClient.OWChatServiceReference.removeFromFriendsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessage", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class sendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string friendName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyString;
        
        public sendMessageRequest() {
        }
        
        public sendMessageRequest(string friendName, string message, string keyString) {
            this.friendName = friendName;
            this.message = message;
            this.keyString = keyString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerUser", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class registerUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public registerUserRequest() {
        }
        
        public registerUserRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerUserResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class registerUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public registerUserResponse() {
        }
        
        public registerUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signIn", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class signInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public signInRequest() {
        }
        
        public signInRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signInResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class signInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public signInResponse() {
        }
        
        public signInResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllUsers", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class getAllUsersRequest {
        
        public getAllUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllUsersResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class getAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getAllUsersResponse() {
        }
        
        public getAllUsersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFriends", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class getAllFriendsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyString;
        
        public getAllFriendsRequest() {
        }
        
        public getAllFriendsRequest(string keyString) {
            this.keyString = keyString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFriendsResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class getAllFriendsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getAllFriendsResponse() {
        }
        
        public getAllFriendsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resetChatServer", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class resetChatServerRequest {
        
        public resetChatServerRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resetChatServerResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class resetChatServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public resetChatServerResponse() {
        }
        
        public resetChatServerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signOut", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class signOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyString;
        
        public signOutRequest() {
        }
        
        public signOutRequest(string keyString) {
            this.keyString = keyString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signOutResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class signOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public signOutResponse() {
        }
        
        public signOutResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAsFriend", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class addAsFriendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string friendName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyString;
        
        public addAsFriendRequest() {
        }
        
        public addAsFriendRequest(string friendName, string keyString) {
            this.friendName = friendName;
            this.keyString = keyString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAsFriendResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class addAsFriendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addAsFriendResponse() {
        }
        
        public addAsFriendResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://source.owchat/")]
    public partial class message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string toField;
        
        private string fromField;
        
        private string bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveMessages", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class receiveMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyString;
        
        public receiveMessagesRequest() {
        }
        
        public receiveMessagesRequest(string keyString) {
            this.keyString = keyString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveMessagesResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class receiveMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public message[] @return;
        
        public receiveMessagesResponse() {
        }
        
        public receiveMessagesResponse(message[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unregisterUser", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class unregisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyString;
        
        public unregisterUserRequest() {
        }
        
        public unregisterUserRequest(string keyString) {
            this.keyString = keyString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unregisterUserResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class unregisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public unregisterUserResponse() {
        }
        
        public unregisterUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeFromFriends", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class removeFromFriendsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string friendName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyString;
        
        public removeFromFriendsRequest() {
        }
        
        public removeFromFriendsRequest(string friendName, string keyString) {
            this.friendName = friendName;
            this.keyString = keyString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeFromFriendsResponse", WrapperNamespace="http://source.owchat/", IsWrapped=true)]
    public partial class removeFromFriendsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://source.owchat/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeFromFriendsResponse() {
        }
        
        public removeFromFriendsResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface OWChatChannel : ChatClient.OWChatServiceReference.OWChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OWChatClient : System.ServiceModel.ClientBase<ChatClient.OWChatServiceReference.OWChat>, ChatClient.OWChatServiceReference.OWChat {
        
        public OWChatClient() {
        }
        
        public OWChatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OWChatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OWChatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OWChatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.sendMessageResponse ChatClient.OWChatServiceReference.OWChat.sendMessage(ChatClient.OWChatServiceReference.sendMessageRequest request) {
            return base.Channel.sendMessage(request);
        }
        
        public bool sendMessage(string friendName, string message, string keyString) {
            ChatClient.OWChatServiceReference.sendMessageRequest inValue = new ChatClient.OWChatServiceReference.sendMessageRequest();
            inValue.friendName = friendName;
            inValue.message = message;
            inValue.keyString = keyString;
            ChatClient.OWChatServiceReference.sendMessageResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).sendMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.registerUserResponse ChatClient.OWChatServiceReference.OWChat.registerUser(ChatClient.OWChatServiceReference.registerUserRequest request) {
            return base.Channel.registerUser(request);
        }
        
        public bool registerUser(string userName, string password) {
            ChatClient.OWChatServiceReference.registerUserRequest inValue = new ChatClient.OWChatServiceReference.registerUserRequest();
            inValue.userName = userName;
            inValue.password = password;
            ChatClient.OWChatServiceReference.registerUserResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).registerUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.signInResponse ChatClient.OWChatServiceReference.OWChat.signIn(ChatClient.OWChatServiceReference.signInRequest request) {
            return base.Channel.signIn(request);
        }
        
        public string signIn(string userName, string password) {
            ChatClient.OWChatServiceReference.signInRequest inValue = new ChatClient.OWChatServiceReference.signInRequest();
            inValue.userName = userName;
            inValue.password = password;
            ChatClient.OWChatServiceReference.signInResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).signIn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.getAllUsersResponse ChatClient.OWChatServiceReference.OWChat.getAllUsers(ChatClient.OWChatServiceReference.getAllUsersRequest request) {
            return base.Channel.getAllUsers(request);
        }
        
        public string[] getAllUsers() {
            ChatClient.OWChatServiceReference.getAllUsersRequest inValue = new ChatClient.OWChatServiceReference.getAllUsersRequest();
            ChatClient.OWChatServiceReference.getAllUsersResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).getAllUsers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.getAllFriendsResponse ChatClient.OWChatServiceReference.OWChat.getAllFriends(ChatClient.OWChatServiceReference.getAllFriendsRequest request) {
            return base.Channel.getAllFriends(request);
        }
        
        public string[] getAllFriends(string keyString) {
            ChatClient.OWChatServiceReference.getAllFriendsRequest inValue = new ChatClient.OWChatServiceReference.getAllFriendsRequest();
            inValue.keyString = keyString;
            ChatClient.OWChatServiceReference.getAllFriendsResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).getAllFriends(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.resetChatServerResponse ChatClient.OWChatServiceReference.OWChat.resetChatServer(ChatClient.OWChatServiceReference.resetChatServerRequest request) {
            return base.Channel.resetChatServer(request);
        }
        
        public bool resetChatServer() {
            ChatClient.OWChatServiceReference.resetChatServerRequest inValue = new ChatClient.OWChatServiceReference.resetChatServerRequest();
            ChatClient.OWChatServiceReference.resetChatServerResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).resetChatServer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.signOutResponse ChatClient.OWChatServiceReference.OWChat.signOut(ChatClient.OWChatServiceReference.signOutRequest request) {
            return base.Channel.signOut(request);
        }
        
        public bool signOut(string keyString) {
            ChatClient.OWChatServiceReference.signOutRequest inValue = new ChatClient.OWChatServiceReference.signOutRequest();
            inValue.keyString = keyString;
            ChatClient.OWChatServiceReference.signOutResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).signOut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.addAsFriendResponse ChatClient.OWChatServiceReference.OWChat.addAsFriend(ChatClient.OWChatServiceReference.addAsFriendRequest request) {
            return base.Channel.addAsFriend(request);
        }
        
        public bool addAsFriend(string friendName, string keyString) {
            ChatClient.OWChatServiceReference.addAsFriendRequest inValue = new ChatClient.OWChatServiceReference.addAsFriendRequest();
            inValue.friendName = friendName;
            inValue.keyString = keyString;
            ChatClient.OWChatServiceReference.addAsFriendResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).addAsFriend(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.receiveMessagesResponse ChatClient.OWChatServiceReference.OWChat.receiveMessages(ChatClient.OWChatServiceReference.receiveMessagesRequest request) {
            return base.Channel.receiveMessages(request);
        }
        
        public message[] receiveMessages(string keyString) {
            ChatClient.OWChatServiceReference.receiveMessagesRequest inValue = new ChatClient.OWChatServiceReference.receiveMessagesRequest();
            inValue.keyString = keyString;
            ChatClient.OWChatServiceReference.receiveMessagesResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).receiveMessages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.unregisterUserResponse ChatClient.OWChatServiceReference.OWChat.unregisterUser(ChatClient.OWChatServiceReference.unregisterUserRequest request) {
            return base.Channel.unregisterUser(request);
        }
        
        public bool unregisterUser(string keyString) {
            ChatClient.OWChatServiceReference.unregisterUserRequest inValue = new ChatClient.OWChatServiceReference.unregisterUserRequest();
            inValue.keyString = keyString;
            ChatClient.OWChatServiceReference.unregisterUserResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).unregisterUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.OWChatServiceReference.removeFromFriendsResponse ChatClient.OWChatServiceReference.OWChat.removeFromFriends(ChatClient.OWChatServiceReference.removeFromFriendsRequest request) {
            return base.Channel.removeFromFriends(request);
        }
        
        public bool removeFromFriends(string friendName, string keyString) {
            ChatClient.OWChatServiceReference.removeFromFriendsRequest inValue = new ChatClient.OWChatServiceReference.removeFromFriendsRequest();
            inValue.friendName = friendName;
            inValue.keyString = keyString;
            ChatClient.OWChatServiceReference.removeFromFriendsResponse retVal = ((ChatClient.OWChatServiceReference.OWChat)(this)).removeFromFriends(inValue);
            return retVal.@return;
        }
    }
}
