/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JavaMessenger.java
 *
 * Created on Sep 13, 2010, 1:28:59 PM
 */

package javachatclient;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javachatclient.UserChat;
import javax.swing.JOptionPane;
import owchat.source.Message;

/**
 *
 * @author KPathirana
 */
public class JavaMessenger extends javax.swing.JFrame {

   // Vector chatList = new Vector();
    static String key = null;
    String username = null;
//    ChatService newList = new ChatService();
    Vector chatlist = new Vector();
    static List<Message> messages = new ArrayList<Message>();
    static ArrayList<UserChat> openChats= new ArrayList();
//    static UserChat[] openChats = new UserChat[10];
    //static String[] openWindows = null;
//    static Map<String , Integer> openWindows = new HashMap();
    

    /** Creates new form JavaMessenger */
    public JavaMessenger() {
    }

    public JavaMessenger(Vector chatList, String key, String username){
        initComponents();

        this.key = key;
        this.username = username;
        this.chatlist = chatList;
        this.setTitle(username + " is Available");
        jChatList.setListData(chatList);

//        ChatMessage recieve = new ChatMessage(key);


         ChatService recieve = ChatService.getInstanceWithKey(key);
        new Thread(recieve).start();
        messages = recieve.recieveMessages(key);
 
        
//        this.recieveMessages();

//        Thread recieve = new Thread(new ChatMessage());
//        recieve.start();
        //messages = newList.recieveMessages(key);

       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jChatList = new javax.swing.JList();
        jChat = new javax.swing.JButton();
        jAddFriends = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        jLogout = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jChatList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jChatList.setName("jChatList"); // NOI18N
        jScrollPane1.setViewportView(jChatList);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javachatclient.JavaChatClientApp.class).getContext().getResourceMap(JavaMessenger.class);
        jChat.setText(resourceMap.getString("jChat.text")); // NOI18N
        jChat.setName("jChat"); // NOI18N
        jChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChatActionPerformed(evt);
            }
        });

        jAddFriends.setText(resourceMap.getString("jAddFriends.text")); // NOI18N
        jAddFriends.setName("jAddFriends"); // NOI18N
        jAddFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddFriendsActionPerformed(evt);
            }
        });

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        jLogout.setText(resourceMap.getString("jLogout.text")); // NOI18N
        jLogout.setName("jLogout"); // NOI18N
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        fileMenu.add(jLogout);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(javachatclient.JavaChatClientApp.class).getContext().getActionMap(JavaMessenger.class, this);
        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(jAddFriends)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChat)
                    .addComponent(jAddFriends))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChatActionPerformed

        String selectedContact = (String) jChatList.getSelectedValue();
        UserChat userChat = new UserChat(selectedContact, key);
        userChat.setVisible(true);
        //openChats[openChats.length] = userChat;
        openChats.add(userChat);

        //new UserChat(selectedContact,key).setVisible(true);
//        openWindows.put(selectedContact, 1);
        
    }//GEN-LAST:event_jChatActionPerformed

    private void jAddFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddFriendsActionPerformed
        new AddFriends(key,username).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jAddFriendsActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        boolean IsSignout;
        if(IsSignout = ChatService.getInstance().signOut(key)){
            JOptionPane.showMessageDialog(null, "You have Successfully Logged out", "Log out Successful", 1);
            System.out.println(IsSignout);
            System.exit(1);
        }
    }//GEN-LAST:event_jLogoutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void closeChatWindow(javax.swing.JFrame jFrame){
//        String name = jFrame.getTitle();
//        openWindows.put(name, 0);
//        jFrame.dispose();
//
//        System.out.println(openWindows);
    }

    public static void recieveMessages(){

//        String keySet = null;

//        for (Iterator<Message> it = messages.iterator(); it.hasNext();) {
//            Message message = it.next();
//
//            String from = message.getFrom();
//
//            Iterator map = openWindows.entrySet().iterator();

//            while (map.hasNext()) {
//
//                //keySet = (String) map.next();
//                Map.Entry pairs = (Entry) map.next();
//                String keyFrom = (String) pairs.getKey();
//                Integer value = (Integer) pairs.getValue();
//
//                if(keyFrom == from && value == 0){
//
//                    new UserChat(message, key);
//
//                }
//
//            }
       // }

//        for (Iterator<Message> it = messages.iterator(); it.hasNext();) {
//            Message message = it.next();
//
//            for (int i = 0; i < openChats.length; i++) {
//
//                if ((openChats[i].getTitle() == message.getFrom())) {
//
//                    if (openChats[i].isVisible()) {
//
//                                openChats[i].getMessage(message);
//
//                    } else {
//
//                        UserChat userChat = new UserChat(message, key);
//                        userChat.setVisible(true);
//                        openChats[1] = userChat;
//                        break;
//
//                    }
//
//                }
//            }
//
//        }

        for (Iterator<Message> itMessage = messages.iterator(); itMessage.hasNext();) {
            Message message = itMessage.next();

            for (Iterator<UserChat> itChats = openChats.iterator(); itChats.hasNext();) {
                UserChat chatWindow = itChats.next();

                if (message.getFrom() == chatWindow.getTitle() && chatWindow.isVisible()){

                         chatWindow.getMessage(message);
                         messages.remove(message);
                         break;

                } else {

                        //openChats.remove(chatWindow);
                        UserChat userChat = new UserChat(message, key);
                        userChat.setVisible(true);
                        openChats.add(userChat);
                        messages.remove(message);
                        break;

                    
//                else {
//
//                     UserChat userChat = new UserChat(message, key);
//                     userChat.setVisible(true);
//                     openChats.add(userChat);
//
//                }

                }
            }
            return;
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaMessenger().setVisible(true);
//                ChatMessage recieve = new ChatMessage(key);
//                new Thread(recieve).start();
//                messages = recieve.recieveMessages(key);

//                while(true){
//                JavaMessenger.recieveMessages();
//                System.out.println(messages);
//                }
                while (true) {

                    recieveMessages();

                }

    }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddFriends;
    private javax.swing.JButton jChat;
    private javax.swing.JList jChatList;
    private javax.swing.JMenuItem jLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
